variables:
  CI_DOCKERHUB_IMAGE: huncrys/anope

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/kaniko-build@~latest
    inputs:
      licenses: GPL-2.0
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/manifest-tool-manifest@~latest
